package Interfaces;

import Controles.GerenciadorDeProdutos;
import Modelos.Produto;
import Modelos.Tabela;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class CadastroProduto extends javax.swing.JFrame {

    GerenciadorDeProdutos produto = new GerenciadorDeProdutos();
    private Produto produtoAntigo, produtoRemover;

    public CadastroProduto() {
        initComponents();
        preencherTabela(produto.getProdutos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuClientes1 = new javax.swing.JMenu();
        MenuCaixa = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        tfNome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tfNome.setCaretColor(new java.awt.Color(255, 255, 255));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(118, 40, 291, 30);

        tfPreco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(tfPreco);
        tfPreco.setBounds(296, 86, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tabelaProdutos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 187, 453, 152);

        btnPesquisar.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa35x35.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(590, 86, 35, 35);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(120, 130, 105, 30);

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(320, 130, 61, 30);

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(240, 130, 63, 30);

        btnRemover.setText("Remover");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(400, 130, 90, 30);

        tfPesquisa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(tfPesquisa);
        tfPesquisa.setBounds(474, 86, 110, 30);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Produtos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Preço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pesquisa:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Código:");

        tfCodigo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 360);

        MenuClientes1.setText("Novo produto");
        MenuClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuProdutoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuClientes1);

        MenuCaixa.setText("Nova venda");
        MenuCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCaixaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCaixa);

        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(703, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        produtoAntigo = capturaProduto();
        if (produtoAntigo != null) {
            tfNome.setText(produtoAntigo.getNome());
            tfCodigo.setText(Integer.toString(produtoAntigo.getCodigo()));
            tfPreco.setText(Float.toString(produtoAntigo.getPreco()));
            btnCadastrar.setEnabled(false);
            btnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        // TODO add your handling code here:
        btnEditar.setEnabled(true);
        btnRemover.setEnabled(true);
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void MenuCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCaixaMouseClicked
        // TODO add your handling code here:
        Venda frm = new Venda();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuCaixaMouseClicked

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_MenuSairMouseClicked

    private void MenuProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProdutoMouseClicked
        // TODO add your handling code here:
        CadastroProduto frm = new CadastroProduto();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuProdutoMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nome = tfNome.getText();
            float preco = Float.parseFloat(tfPreco.getText());
            int codigo = Integer.parseInt(tfCodigo.getText());
            // Verifica se o código digitado já está cadastrado
            Produto produtoAux = produto.pesquisar(tfCodigo.getText());
            if (produtoAux.getNome() == null) {
                produto.cadastrar(nome, preco, codigo);
                preencherTabela(produto.getProdutos());
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Codigo de produto já cadastrado!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            limparCampos();
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto!");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Produto novo = new Produto(tfNome.getText(), Float.parseFloat(tfPreco.getText()), Integer.parseInt(tfCodigo.getText()));
            produto.editar(produtoAntigo, novo);
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
            preencherTabela(produto.getProdutos());
            limparCampos();
            btnSalvar.setEnabled(false);
            btnCadastrar.setEnabled(true);
            btnEditar.setEnabled(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar produto!");
            limparCampos();
            btnSalvar.setEnabled(false);
            btnCadastrar.setEnabled(true);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        produtoRemover = capturaProduto();
        int resultado = JOptionPane.showConfirmDialog(null, "Confirmar remoção do produto?", "REMOÇÃO DE PRODUTO", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            produto.remover(produtoRemover);
            preencherTabela(produto.getProdutos());
            limparCampos();
            btnRemover.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnCadastrar.setEnabled(true);
            btnEditar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Produto removido com sucesso!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        int tamanhoPesquisa = tfPesquisa.getText().length();
        ArrayList pesquisa = produto.pesquisar(tfPesquisa.getText(), tamanhoPesquisa);
        // Verifica se a lista retornada contem elementos
        if (!pesquisa.isEmpty()) {
            preencherTabela(pesquisa);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto localizado!");
            preencherTabela(produto.getProdutos());
            limparCampos();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    // Metodo para capturar produto selecionado da tabela
    public Produto capturaProduto() {
        String nomeTabela = "" + tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1);
        String codigoTabela = "" + tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0);
        String precoTabela = "" + tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2);
        Produto produtoTabela = new Produto(nomeTabela, Float.parseFloat(precoTabela), Integer.parseInt(codigoTabela));
        return produtoTabela;
    }

    // Metodo para limpar campos de texto
    public void limparCampos() {
        tfNome.setText("");
        tfPreco.setText("");
        tfCodigo.setText("");
        tfPesquisa.setText("");
    }

    // Metodo para preencher tabela de produtos
    public void preencherTabela(ArrayList<Produto> produtos) {
        produto = new GerenciadorDeProdutos();
        ArrayList dados = new ArrayList();

        // Define o nome de cada coluna
        String[] Colunas = new String[]{"Código", "Nome", "Preço"};

        // Percorre a lista de produtos na comanda
        for (Produto produto : produtos) {
            dados.add(new Object[]{produto.getCodigo(), produto.getNome(), produto.getPreco()});
        }

        // Cria um modelo da tabela
        Tabela modelo = new Tabela(dados, Colunas);

        /*
        Define a tabela de acordo com o modelo passado
        Seta os paramêtros da tabela(tamanho das colunas)
        Não é permitido ao usuario modificar ordem das colunas
        As colunas se redimensionam para preencher o espaço reservado
        Apenas um item selecionado por vez
         */
        tabelaProdutos.setModel(modelo);
        tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(83);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        tabelaProdutos.setAutoResizeMode(tabelaProdutos.AUTO_RESIZE_OFF);
        tabelaProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCaixa;
    private javax.swing.JMenu MenuClientes1;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfPreco;
    // End of variables declaration//GEN-END:variables
}
